#!/usr/bin/env bash
# Idempotent CI bootstrap for dxAgent Linux: PATH, uv/uvx, cursor-sdk, MCP wheel cache.
# Source from any pipeline step, or run via verify-checkout.sh.
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-${PWD}}"
MARKER="${REPO_ROOT}/.teamcity-ci/bootstrap.env"
UV_INSTALL_DIR="${UV_INSTALL_DIR:-${HOME}/.local/bin}"

_corner_ci_prepend_path() {
  local dir
  for dir in "${UV_INSTALL_DIR}" "${HOME}/.local/bin" "${HOME}/.cargo/bin"; do
    if [ -d "$dir" ]; then
      case ":${PATH}:" in
        *":${dir}:"*) ;;
        *) PATH="${dir}:${PATH}" ;;
      esac
    fi
  done
  export PATH
}

_corner_ci_install_uv() {
  if command -v uvx >/dev/null 2>&1; then
    echo "uvx: $(command -v uvx) ($(uvx --version 2>/dev/null || true))"
    return 0
  fi
  if command -v uv >/dev/null 2>&1; then
    echo "uv: $(command -v uv) ($(uv --version 2>/dev/null || true))"
    return 0
  fi

  echo "uv/uvx not on PATH — installing to ${UV_INSTALL_DIR} …"
  mkdir -p "${UV_INSTALL_DIR}"

  if command -v curl >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${UV_INSTALL_DIR}" sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${UV_INSTALL_DIR}" sh
  else
    echo "ERROR: curl or wget required to bootstrap uv on the agent" >&2
    return 1
  fi

  _corner_ci_prepend_path
  if ! command -v uvx >/dev/null 2>&1 && ! command -v uv >/dev/null 2>&1; then
    echo "ERROR: uv install finished but uvx/uv still not on PATH" >&2
    return 1
  fi
  echo "uv bootstrap OK: $(command -v uvx 2>/dev/null || command -v uv)"
}

_corner_ci_install_cursor_sdk() {
  if ! python3 -m pip --version >/dev/null 2>&1; then
    python3 -m ensurepip --user --default-pip 2>/dev/null || true
  fi
  python3 -m pip install --user -q --upgrade pip
  python3 -m pip install --user -q cursor-sdk
  _corner_ci_prepend_path
  if ! python3 -c "import cursor_sdk" 2>/dev/null; then
    echo "ERROR: cursor-sdk import failed after pip install" >&2
    return 1
  fi
  echo "cursor-sdk OK"
}

_corner_ci_resolve_uvx() {
  _corner_ci_prepend_path
  if command -v uvx >/dev/null 2>&1; then
    UVX_BIN="$(command -v uvx)"
    UVX_MODE="uvx"
  elif command -v uv >/dev/null 2>&1; then
    UVX_BIN="$(command -v uv)"
    UVX_MODE="uv-x"
  else
    echo "ERROR: neither uvx nor uv available after bootstrap" >&2
    return 1
  fi
  export UVX_BIN
  export UVX_MODE
}

_corner_ci_prefetch_mcp() {
  local rc=0
  echo "Warming uv cache for mcp-atlassian-with-bitbucket (up to 120s) …"
  set +e
  if [ "${UVX_MODE}" = "uv-x" ]; then
    timeout 120 "${UVX_BIN}" x --with 'fakeredis<2.35' mcp-atlassian-with-bitbucket </dev/null >/dev/null 2>&1
    rc=$?
  else
    timeout 120 "${UVX_BIN}" --with 'fakeredis<2.35' mcp-atlassian-with-bitbucket </dev/null >/dev/null 2>&1
    rc=$?
  fi
  set -e
  case "$rc" in
    0|124|143) echo "MCP wheel cache warm OK (exit ${rc})" ;;
    *) echo "WARN: MCP prefetch exit ${rc} — agent step may download on first use" ;;
  esac
}

_corner_ci_write_marker() {
  mkdir -p "$(dirname "${MARKER}")"
  cat >"${MARKER}" <<EOF
# Generated by bootstrap-agent-env.sh — do not commit
export PATH="${PATH}"
export UVX_BIN="${UVX_BIN}"
export UVX_MODE="${UVX_MODE:-uvx}"
export CORNER_CI_BOOTSTRAP=1
EOF
  echo "Wrote ${MARKER}"
}

_corner_ci_bootstrap() {
  _corner_ci_prepend_path

  if [ -f "${MARKER}" ] && [ "${CORNER_CI_FORCE_BOOTSTRAP:-0}" != "1" ]; then
  # shellcheck source=/dev/null
    . "${MARKER}"
    _corner_ci_prepend_path
    if command -v "${UVX_BIN:-uvx}" >/dev/null 2>&1 && python3 -c "import cursor_sdk" 2>/dev/null; then
      echo "CI bootstrap cache hit (${MARKER})"
      return 0
    fi
    echo "CI bootstrap cache stale — re-running full bootstrap"
  fi

  _corner_ci_install_uv
  _corner_ci_resolve_uvx
  _corner_ci_install_cursor_sdk
  _corner_ci_prefetch_mcp
  _corner_ci_write_marker
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  _corner_ci_bootstrap
else
  _corner_ci_bootstrap
fi
